### ISSUE TITLE
Remove new Function

### ISSUE THREAD

**Issue by glensc** [davipon/esbuild-plugin-pino#38]
Why can't just create a function without doing `new Function` which kind of is equivalent of `eval()`:

- https://github.com/davipon/esbuild-plugin-pino/blob/118b7c3f46c442ae9f22e1e991eac87109b6b9ef/src/index.ts#L114

```ts
    function pinoBundlerAbsolutePath(p) {
      try {
        return require("path").join(`${process.cwd()}${require("path").sep}dist`.replace(/\\/g, "/"), p);
      } catch (e) {
        const f = (p) => new URL(p, import.meta.url).pathname;
        return f(p);
      }
    }

```

**Comment by davipon** [comment]
I tried and I got a serialize error when building the app.
![error message](https://drive.google.com/uc?id=1br5YCS50FtT3H7Asd8FpB2iJQ8KkN4Uy)

If you have any clue and know how to fix it, PR is welcome.
