### ISSUE TITLE
pino-pretty nor really bundled with SvelteKit build

### ISSUE THREAD

**Issue by PlkMarudny** [davipon/esbuild-plugin-pino#62]
I tried to use the plugin with SvelteKit, and was somehow successful, except that the bundled app apparently cannot find _pino-pretty_, I received this during the start of application:

`Error: unable to determine transport target for "pino-pretty"`

**Comment by davipon** [comment]
That’s an interesting use case!
May I know the reason you use this library with SvelteKit?

**Comment by PlkMarudny** [comment]
I have a custom Node server for SvelteKit (because of Web Sockets) and I
use Pino with it, so basically Pino lands in my SvelteKit app. But it does
not work in the production build (unless kept in dependencies, not dev
dependencies, but in that case the whole node_modules adds 900MB of the
container size).

**Comment by davipon** [comment]
You're right. While `pino-pretty` doesn't recommend installing it as dep but devDep [here](https://github.com/pinojs/pino-pretty#programmatic-integration). 

Not sure how you build your docker image, in my use case, I bundled my fastify app (`pino-pretty` in dep) and only copied production code w/o `node_modules` in my `Dockerfile`, and my docker image only used 180 MB.

**Comment by PlkMarudny** [comment]
Right, however I cannot make it work somehow. There is always something
pino is complaining about, unless I copy the whole node_volumes. No
worries, at the end I just replaced pino with loglevel; unfortunately I
cannot get rid of logging altogether, but for the time being it is fine.
Will try to investigate that later.

Tomasz Plonka
