### ISSUE TITLE
esbuild 0.16.7 needs another release of this plugin

### ISSUE THREAD

**Issue by gunters63** [davipon/esbuild-plugin-pino#68]
Its me again :)

0.16.6 still worked. Seems the API changed again.

![image](https://user-images.githubusercontent.com/90346/208612271-c42c8957-27af-4d47-b119-fcf9dfd7e0bc.png)

![image](https://user-images.githubusercontent.com/90346/208612283-125635dc-5c08-4e16-8247-10479e9565ee.png)

**Comment by gunters63** [comment]
Btw, I saw the last issue of this kind mentioned here: https://github.com/evanw/esbuild/issues/2544

Interesting, I am starting to pin Esbuilds version now (which I normally try to avoid).

**Comment by davipon** [comment]
@gunters63 I agree with the author of esbuild. I'm ok with that.

**Comment by gunters63** [comment]
@davipon:  Thank you for the update.

Your plugin is very helpful for an embedded application I develop (graphql-helix, envelop, fastify, prisma).
I couldn't have switched so easily from express to fastify without it :)

**Comment by davipon** [comment]
@gunters63 Appreciate your kind words! It made my day.

Interestingly, I once saw Matteo (author of pino and fastify) talk about bundling and logging in production, and he doesn't recommend doing so. (Sorry, I couldn't find the source.)

This library enables both 😅, but it did solve use cases like deploying a tiny app as a serverless/ edge function, which is hard if you don't bundle. Besides, pino does have an outstanding performance with less overhead. It works perfectly in production, at least in my experience.

**Comment by gunters63** [comment]
@davipon : Our application runs on a arm-based industrial controller from a SD card. No way we want to install a node_modules folder there 😄 

![image](https://user-images.githubusercontent.com/90346/208792575-f7856e2e-63e0-4b2e-bd50-21ba142bc540.png)
